### ISSUE TITLE
Тестирование

### ISSUE THREAD

**Issue by alinagaripova** [alinagaripova/homework.exercise4-wallpapers#5]
@coursar, как тестировать функцию reactToClick в app.js, если нет входных данных и почему без 
 этого тестирования покрытие кода показывает 100%?

https://github.com/alinagaripova/homework.exercise4-wallpapers/blob/c793f08e53b030398598481c4b3e64f5026af5ea/src/js/app.js#L11-L47

**Comment by coursar** [comment]
Пока app.js не тестируем. Потому что, если вы просто используете jest --coverage, то он считает только покрытие по тем файлам, которые вы тестируете
